spark-swagger {
  theme="FLATTOP"
  deepLinking=false
  defaultModelsExpandDepth=1
  defaultModelExpandDepth=1
  defaultModelRendering="example"
  displayOperationId=false
  displayRequestDuration=true
  docExpansion="FULL"
  filter=false
  operationsSorter="alpha"
  showExtensions=false
  showCommonExtensions=false
  tagsSorter="alpha"

  host="localhost:8080"
  basePath="/recipe"
  info {
    title="Recipe API"
    description="A recipe API powered by Spark Java Framework"
    version="${project.version}"
    termsOfService=""
    schemes=["HTTP","HTTPS"]
    project {
      groupId="${project.groupId}"
      artifactId="${project.artifactId}"
      version="${project.version}"
    }
  }
}